baseURL: 'https://vmdude.github.io/lesbrousses/public/'
languageCode: fr
title: Gîte Les Brousses
theme: hargo
enableInlineShortcodes: true
disableKinds: taxonomy
ignoreErrors: error-disable-taxonomy
# summaryLength: '20'
# paginate: 10
# disqusShortname: ''
params:
  geo:
    title       : Les Brousses
    # Use pixel for width as well
    width       : 100%
    height      : 500
    pre_embed   : https://www.openstreetmap.org/export/embed.html?
    embed       : bbox=0.48554420471191406%2C45.14315339060149%2C0.49170792102813726%2C45.14562789448083&amp;layer=mapnik&marker=45.14439065596734%2C0.48862606287002563
    map_big     : https://www.openstreetmap.org/?mlat=45.14439&amp;mlon=0.48863#map=18/45.14439/0.48863
    map_big_text: Agrandir la carte (et accéder aux directions)
  plugins:
    css:
      # - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/fancybox/jquery.fancybox.min.css
    js:
      # - link: plugins/jQuery/jquery.min.js
      - link: plugins/jQuery/jquery-3.6.0.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/fancybox/jquery.fancybox-3.5.7.min.js
      # - link: plugins/loading-attribute-polyfill/loading-attribute-polyfill.module.js
      # - link: plugins/loading-attribute-polyfill/loading-attribute-polyfill.js
      # - link: plugins/loading-attribute-polyfill/loading-attribute-polyfill.umd.js
      # - link: plugins/loading-attribute-polyfill/loading-attribute-polyfill.modern.js
  logo: images/logo.png
  home: Accueil
  description: Gite Les Brousses
  author: SCI Les Brousses
  # gmapAPI: >-
  #   https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
  # mapLatitude: '51.5223477'
  # mapLongitude: '-0.1622023'
  # mapMarker: images/marker.png
  googleAnalitycsID: ''
  mobile: '+33553039863'
  email: contact@lesbrousses.fr
  location: 'Les Brousses, 24110 Saint-Astier'
  copyright: >-
    Copyright &copy; 2021 [SCI Les Brousses](https://www.lesbrousses.fr) Tout droits réservés
  # snipcartApiKey: ''
  # currencySymbol: $
  preloader:
    enable: true
    preloader: images/logo.png
  # rating:
  #   enable: true
  #   websiteID: '444334'
  #   publicKey: 811cf0927332bf51f2e12f84608594ac
  # social:
  #   - icon: ti-facebook
  #     link: '#'
  #   - icon: ti-twitter-alt
  #     link: '#'
  #   - icon: ti-youtube
  #     link: '#'
  #   - icon: ti-instagram
  #     link: '#'
  #   - icon: ti-pinterest
  #     link: '#'
  contact:
    formAction: 'https://formspree.io/f/xaylrbab'
menu:
  main:
    - name: Les Brousses
      URL: lesbrousses
      weight: 1
    - name: Grange
      URL: grange
      weight: 2
    - name: Bergerie
      URL: bergerie
      weight: 3
    - name: Activités
      URL: activites
      weight: 4
    - name: Disponibilités
      URL: disponibilites
      weight: 5
    - name: Livre d'or
      URL: livredor
      weight: 6
    - name: Actualités
      URL: actualites
      weight: 7
    - name: Contact
      URL: contact
      weight: 8
  # footer:
  #   - name: Products
  #     URL: products
  #     weight: 1
  #   - name: Blog
  #     URL: blog
  #     weight: 2
  #   - name: FAQ
  #     URL: faq
  #     weight: 3
  #   - name: Terms & Conditions
  #     URL: terms-conditions
  #     weight: 4
  #   - name: Contact
  #     URL: contact
  #     weight: 5
