baseURL: 'https://vmdude.github.io/hellocloud/'
title: HelloCloud
theme: meghna-hugo
# paginate: '6'
canonifyURLs: true
# summaryLength: '15'
# disqusShortname: ''
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: >-
          https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  logo: images/logo.png
  description: Bienvenue chez HelloCloud
  copyright: © 2020 HelloCloud
  author: HelloCloud
  # google_analitycs_id: ''
  post_share: false
  preloader:
    enable: true
    preloader: images/logo.png
  map:
    enable: false
    # gmap_api: >-
    #   https://maps.googleapis.com/maps/api/js?key=AIzaSyBabIhebg_Lr9yCf6qDO9jvctm_OFk5Wug
    # map_latitude: '48.880570'
    # map_longitude: '2.326960'
    # map_marker: images/marker.png
  # social:
  #   - icon: ti-facebook
  #     link: '#'
  #   - icon: ti-twitter-alt
  #     link: '#'
  #   - icon: ti-youtube
  #     link: '#'
  #   - icon: ti-linkedin
  #     link: '#'
  #   - icon: ti-dribbble
  #     link: '#'
  #   - icon: ti-pinterest
  #     link: '#'
menu:
  main:
    - name: Cloud
      URL: cloud
      weight: 1
    - name: Messagerie
      URL: messagerie
      weight: 2
    - name: Sauvegarde
      URL: sauvegarde
      weight: 3
    - name: Consulting
      URL: consulting
      weight: 4
    - name: Contact
      URL: contact
      weight: 5
    - name: Recrutement
      URL: recrutement
      weight: 6
    - name: A Propos
      URL: a-propos
      weight: 7
