######################## default configuration ####################
baseURL = "https://vmdude.github.io/ligare/public/"
languageCode = "fr-FR"
title = "Hargo | Hugo Ecommerce Site"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  # [[menu.main]]
  # name = "Entretiens"
  # URL = "entretiens"
  # weight = 2

  [[menu.main]]
  identifier = "association"
  name = "L'Association"
  URL = "association"
  weight = 1

  [[menu.main]]
  parent = "association"
  name = "L'Association"
  URL = "association"
  weight = 11

  [[menu.main]]
  parent = "association"
  name = "Philosophie"
  URL = "philosophie"
  weight = 12

  [[menu.main]]
  parent = "association"
  name = "Qui sommes nous ?"
  URL = "qui-sommes-nous"
  weight = 13

  [[menu.main]]
  parent = "association"
  name = "Actualités"
  URL = "actualites"
  weight = 14

  [[menu.main]]
  parent = "association"
  name = "Partenaires"
  URL = "partenaires"
  weight = 15

  # [[menu.main]]
  # parent = "association"
  # name = "Soutiens"
  # URL = "soutiens"
  # weight = 34

  [[menu.main]]
  identifier = "accompagnement-des-familles"
  name = "Accompagnement des familles"
  URL = "accompagnement-des-familles"
  weight = 2

  [[menu.main]]
  parent = "accompagnement-des-familles"
  name = "Consultations"
  URL = "consultations"
  weight = 21

  [[menu.main]]
  parent = "accompagnement-des-familles"
  name = "Groupe de paroles"
  URL = "groupe-de-parole"
  weight = 22

  [[menu.main]]
  parent = "accompagnement-des-familles"
  name = "Calendriers"
  URL = "calendriers"
  weight = 23

  [[menu.main]]
  name = "Accompagnement des professionnels"
  URL = "accompagnement-des-professionnels"
  weight = 3

  [[menu.main]]
  name = "Dons"
  URL = "dons"
  weight = 4

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/assoc_ligare.png"
home = "Accueil"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "Dhaka, Bangladedsh"
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "images/assoc_ligare.png" # use .png , .svg or .gif format

# Product Rating
# it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
[params.rating]
enable = false
websiteID = "444334"
publicKey = "811cf0927332bf51f2e12f84608594ac"

# Social Site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-youtube"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "ti-pinterest"
link = "#"

# Contact Form
[params.contact]
formAction = "#" # contact form works with formspree.io