################################# Default configuration ###################
baseURL = "https://vmdude.github.io/hellocloud/"
title = "HelloCloud"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
disqusShortname = "" # get your shortname form here : https://disqus.com

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "Cloud"
URL = "cloud"
weight = 1

[[menu.main]]
name = "Messagerie"
URL = "messagerie"
weight = 2

[[menu.main]]
name = "Sauvegarde"
URL = "sauvegarde"
weight = 3

[[menu.main]]
name = "Consulting"
URL = "consulting"
weight = 4

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 5

[[menu.main]]
name = "Recrutement"
URL = "recrutement"
weight = 6

[[menu.main]]
name = "A Propos"
URL = "a-propos"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Bienvenue chez HelloCloud"
author = "HelloCloud"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBabIhebg_Lr9yCf6qDO9jvctm_OFk5Wug"
map_latitude = "48.880570"
map_longitude = "2.326960"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

