---
# baseURL: https://doc.poligraf.io/
baseURL: https://vmdude.github.io/poligraf-doc/public/
title: doc.poligraf.io
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
canonifyURLs: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/polibytes/poligraf-doc
  geekdocEditPath: edit/master/content

  geekdocSearch: true

  # geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  # geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
